/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadinhojj.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import mercadinhojj.DAO.ConexaoDAO;
import mercadinhojj.model.ClienteModel;
import mercadinhojj.model.VendaModel;

/**
 *
 * @author kadu
 */
public class HistoricoVendasInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistoricoVendasInternal
     */
     private ConexaoDAO con = new ConexaoDAO();
    public HistoricoVendasInternal() {
        List<VendaModel> lvendas= con.listVendas();
        for(VendaModel lv:lvendas){
            System.out.println("fk_cliente:"+lv.getCliente());
        }
        System.out.println();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelavendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        visualizarAciton = new javax.swing.JButton();

        setClosable(true);

        Object vendas [][]= new Object [totalVendas.size()][4];
        int i =0;
        List<ClienteModel> lclientes=con.listClientes();
        List<VendaModel> lvendas= con.listVendas();
        String clienteAtual="";
        for (VendaModel v: lvendas){
            System.out.println("ID:"+v.getId());
            for(ClienteModel cl: lclientes){
                if(cl.getCPF().equals(v.getCliente())){
                    clienteAtual=cl.getNome();
                }
            }
            vendas[i][0]=v.getId();
            vendas[i][1]=v.getData();
            vendas[i][2]=clienteAtual;
            vendas[i][3]=v.getValorTotal();
            i++;
        }
        tabelavendas.setModel(new javax.swing.table.DefaultTableModel(
            vendas,
            new String [] {
                "ID","Data","Cliente","Valor"
            }
        ));
        jScrollPane1.setViewportView(tabelavendas);

        jLabel1.setText("Historico de Vendas");

        visualizarAciton.setText("Visualizar");
        visualizarAciton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarAcitonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualizarAciton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(visualizarAciton)
                        .addGap(143, 143, 143)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarAcitonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarAcitonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HistoricoCliente hc= new HistoricoCliente();
        area.add(hc);
        hc.setVisible(true);
    }//GEN-LAST:event_visualizarAcitonActionPerformed

    private JDesktopPane area= mercadinhojj.view.MercadoView.area;
    private static ArrayList<VendaModel> totalVendas= mercadinhojj.view.MercadoView.totalVendas;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelavendas;
    private javax.swing.JButton visualizarAciton;
    // End of variables declaration//GEN-END:variables
}
