/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadinhojj.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mercadinhojj.model.ProdutoModel;
import mercadinhojj.DAO.ConexaoDAO;

/**
 *
 * @author kadu
 */
public class ProdutoInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProdutoInternalFrame
     */

    private ConexaoDAO con = new ConexaoDAO();

    public ProdutoInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nometxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precotxt = new javax.swing.JTextField();
        qtdtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slotetxt = new javax.swing.JTextField();
        cadastrarprod = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deletarprod = new javax.swing.JButton();

        setClosable(true);

        ArrayList <ProdutoModel> produtos=MercadoView.produtos;

        Object produtosMatriz [][]= new Object[produtos.size()][4];

        for(int i=0;i<produtos.size();i++){
            produtosMatriz[i][0]=produtos.get(i).getLote();
            produtosMatriz[i][1]=produtos.get(i).getNome();
            produtosMatriz[i][2]=produtos.get(i).getPreco();
            produtosMatriz[i][3]=produtos.get(i).getQuantidade();
        }
        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            produtosMatriz,
            new String [] {
                "Slote", "Produto", "Preço", "Quantidade"
            }
        ));
        tabelaprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaprodutos);

        jLabel1.setText("Produtos");

        jLabel2.setText("Nome");

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Slote");

        cadastrarprod.setText("Cadastrar");
        cadastrarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprodActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        deletarprod.setText("Deletar");
        deletarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precotxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(2, 2, 2)
                                    .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qtdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(slotetxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(deletarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(qtdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(precotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(slotetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletarprod)
                    .addComponent(jButton2)
                    .addComponent(cadastrarprod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprodActionPerformed
        // TODO add your handling code here:
        ProdutoModel p = new ProdutoModel(Integer.parseInt(slotetxt.getText()),nometxt.getText(), Integer.parseInt(qtdtxt.getText()), Double.parseDouble(precotxt.getText()));
        produtos.add(p);
        con.setProduto(p);
     
        DefaultTableModel dtmprodutos= (DefaultTableModel)tabelaprodutos.getModel();
        Object[] dados={slotetxt.getText(),nometxt.getText(),precotxt.getText(),qtdtxt.getText()};
        dtmprodutos.addRow(dados);

        slotetxt.setText(" ");
        nometxt.setText(" ");
        precotxt.setText(" ");
        qtdtxt.setText(" ");
        
    }//GEN-LAST:event_cadastrarprodActionPerformed

    private void deletarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarprodActionPerformed
        // TODO add your handling code here:
        if(tabelaprodutos.getSelectedRow()!=-1){
           produtos.remove(tabelaprodutos.getSelectedRow());
           DefaultTableModel dtmprodutos= (DefaultTableModel)tabelaprodutos.getModel();
           dtmprodutos.removeRow(tabelaprodutos.getSelectedRow());

           ProdutoModel p = new ProdutoModel(Integer.parseInt(slotetxt.getText()),nometxt.getText(), Integer.parseInt(qtdtxt.getText()), Double.parseDouble(precotxt.getText()));
           con.delProduto(p);
           
        }else{
            JOptionPane.showMessageDialog(null,"Selecione algum produto para realizar a ação");
        }
     
    }//GEN-LAST:event_deletarprodActionPerformed

    private void tabelaprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutosMouseClicked
        // TODO add your handling code here:
        int linha= tabelaprodutos.getSelectedRow();
        nometxt.setText(produtos.get(linha).getNome());
        precotxt.setText(Double.toString(produtos.get(linha).getPreco()));
        qtdtxt.setText(Integer.toString(produtos.get(linha).getQuantidade()));
        slotetxt.setText(Integer.toString(produtos.get(linha).getLote()));
        
        
    }//GEN-LAST:event_tabelaprodutosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //atualizar produto
                
        // TODO add your handling code here:
        String nome=nometxt.getText();
        int slote=Integer.parseInt(slotetxt.getText());
        int qtd=Integer.parseInt(qtdtxt.getText());
        double preco=Double.parseDouble(precotxt.getText());
        ProdutoModel novoCliente = new ProdutoModel(slote, nome, qtd, preco);
        con.updateProduto(novoCliente);
        
        int linha = tabelaprodutos.getSelectedRow();
        produtos.remove(tabelaprodutos.getSelectedRow());
        produtos.add(tabelaprodutos.getSelectedRow(),novoCliente);
                
        tabelaprodutos.setValueAt(slotetxt.getText(), tabelaprodutos.getSelectedRow(),0);
        tabelaprodutos.setValueAt(nometxt.getText(), tabelaprodutos.getSelectedRow(),1);
        tabelaprodutos.setValueAt(precotxt.getText(), tabelaprodutos.getSelectedRow(),2);
        tabelaprodutos.setValueAt(qtdtxt.getText(), tabelaprodutos.getSelectedRow(),3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private ArrayList <ProdutoModel> produtos= MercadoView.produtos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarprod;
    private javax.swing.JButton deletarprod;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nometxt;
    private javax.swing.JTextField precotxt;
    private javax.swing.JTextField qtdtxt;
    private javax.swing.JTextField slotetxt;
    private javax.swing.JTable tabelaprodutos;
    // End of variables declaration//GEN-END:variables
}
