/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadinhojj.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mercadinhojj.model.ProdutoModel;
import mercadinhojj.DAO.ConexaoDAO;

/**
 *
 * @author kadu
 */
public class ProdutoInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProdutoInternalFrame
     */

    private ConexaoDAO con = new ConexaoDAO();

    public ProdutoInternalFrame() {
        List <ProdutoModel>testelist=con.listProdutos();
        for (ProdutoModel p : testelist){
            System.out.println("Lote:"+p.getLote());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nometxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precotxt = new javax.swing.JTextField();
        qtdtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastrarprod = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        deletarprod = new javax.swing.JButton();

        setClosable(true);

        ArrayList <ProdutoModel> produtos=MercadoView.produtos;

        Object produtosMatriz [][]= new Object[produtos.size()][4];

        for(int i=0;i<produtos.size();i++){
            produtosMatriz[i][0]=produtos.get(i).getLote();
            produtosMatriz[i][1]=produtos.get(i).getNome();
            produtosMatriz[i][2]=produtos.get(i).getPreco();
            produtosMatriz[i][3]=produtos.get(i).getQuantidade();
        }
        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            produtosMatriz,
            new String [] {
                "Lote", "Produto", "Preço", "Quantidade"
            }
        ));
        tabelaprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaprodutos);

        jLabel1.setText("Produtos");

        jLabel2.setText("Nome");

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        cadastrarprod.setText("Cadastrar");
        cadastrarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprodActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        deletarprod.setText("Deletar");
        deletarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precotxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(2, 2, 2)
                                    .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(qtdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(deletarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(qtdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletarprod)
                    .addComponent(Atualizar)
                    .addComponent(cadastrarprod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprodActionPerformed
        // TODO add your handling code here:
        ProdutoModel p = new ProdutoModel();
        p.setNome(nometxt.getText());
        p.setPreco(Double.parseDouble(precotxt.getText()));
        p.setQuantidade(Integer.parseInt(qtdtxt.getText()));
       
        con.setProduto(p);
        
        List<ProdutoModel> plist=con.listProdutos();
        p.setLote(plist.get(plist.size()-1).getLote());
        
        produtos.add(p);
        JOptionPane.showMessageDialog(null, "O id novo é: "+plist.get(plist.size()-1).getLote());
     
        DefaultTableModel dtmprodutos= (DefaultTableModel)tabelaprodutos.getModel();
        Object[] dados={plist.get(plist.size()-1).getLote(),nometxt.getText(),precotxt.getText(),qtdtxt.getText()};
        dtmprodutos.addRow(dados);

        
        nometxt.setText(" ");
        precotxt.setText(" ");
        qtdtxt.setText(" ");
        
    }//GEN-LAST:event_cadastrarprodActionPerformed

    private void deletarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarprodActionPerformed
        // TODO add your handling code here:
        if(tabelaprodutos.getSelectedRow()!=-1){
           
           int lote_remove=Integer.parseInt(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(),0).toString());
           
           produtos.remove(tabelaprodutos.getSelectedRow());
           DefaultTableModel dtmprodutos= (DefaultTableModel)tabelaprodutos.getModel();
           dtmprodutos.removeRow(tabelaprodutos.getSelectedRow());
           
           
           
           ProdutoModel p = new ProdutoModel(lote_remove,nometxt.getText(), Integer.parseInt(qtdtxt.getText()), Double.parseDouble(precotxt.getText()));
           con.delProduto(p);
           
        }else{
            JOptionPane.showMessageDialog(null,"Selecione algum produto para realizar a ação");
        }
     
    }//GEN-LAST:event_deletarprodActionPerformed

    private void tabelaprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutosMouseClicked
        // TODO add your handling code here:
        int linha= tabelaprodutos.getSelectedRow();
        nometxt.setText(produtos.get(linha).getNome());
        precotxt.setText(Double.toString(produtos.get(linha).getPreco()));
        qtdtxt.setText(Integer.toString(produtos.get(linha).getQuantidade()));
        
        
        
    }//GEN-LAST:event_tabelaprodutosMouseClicked

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        //atualizar produto
                
        // TODO add your handling code here:
        String nome=nometxt.getText();
        
        int qtd=Integer.parseInt(qtdtxt.getText());
        double preco=Double.parseDouble(precotxt.getText());
        ProdutoModel novoProduto = new ProdutoModel();
        novoProduto.setNome(nome);
        novoProduto.setPreco(preco);
        novoProduto.setQuantidade(qtd);
        con.updateProduto(novoProduto);
        
        int linha = tabelaprodutos.getSelectedRow();
        produtos.remove(tabelaprodutos.getSelectedRow());
        produtos.add(tabelaprodutos.getSelectedRow(),novoProduto);
                
        tabelaprodutos.setValueAt(nometxt.getText(), tabelaprodutos.getSelectedRow(),1);
        tabelaprodutos.setValueAt(precotxt.getText(), tabelaprodutos.getSelectedRow(),2);
        tabelaprodutos.setValueAt(qtdtxt.getText(), tabelaprodutos.getSelectedRow(),3);
    }//GEN-LAST:event_AtualizarActionPerformed

    private ArrayList <ProdutoModel> produtos= MercadoView.produtos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton cadastrarprod;
    private javax.swing.JButton deletarprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nometxt;
    private javax.swing.JTextField precotxt;
    private javax.swing.JTextField qtdtxt;
    private javax.swing.JTable tabelaprodutos;
    // End of variables declaration//GEN-END:variables
}
